import type { Course } from "@/types/monprof";
import { frame } from "../builders";

/* Cours intégré n°1 — construit à la main pour servir de référence :
   c'est le comportement pédagogique que l'analyseur automatique
   cherche à reproduire sur un cours importé. */

export const POURCENTAGES: Course = {
  id: "pourcentages",
  title: "Les pourcentages",
  subject: "Mathématiques",
  createdAt: 0,
  origin: "seed",
  chapters: [
    { id: "ch1", title: "Comprendre et calculer", conceptIds: ["proportion", "pourcentage", "part-dune-quantite"] },
    { id: "ch2", title: "Aller plus loin", conceptIds: ["variation"] },
  ],
  concepts: {
    /* ─────────────────────────────────────────────────────── */
    proportion: {
      id: "proportion",
      title: "La proportion",
      objective: "Savoir comparer une partie à un total et exprimer le résultat sous forme décimale.",
      level: 1,
      prerequisites: [],
      keywords: ["proportion", "partie", "total", "rapport"],
      explanations: [
        {
          strategy: "simple",
          say: "On commence par la brique de base. Une proportion, ce n'est rien d'autre qu'une comparaison : je prends une partie, je la compare au total. Et pour comparer, on divise. Rien de plus pour l'instant.",
          board: frame(
            "LA PROPORTION",
            "# Définition",
            "Comparer une partie à un total",
            "~",
            "# Formule",
            "= proportion = partie ÷ total",
          ),
        },
        {
          strategy: "exemple",
          say: "Prenons une classe de 20 élèves dont 10 sont des filles. La partie, c'est 10. Le total, c'est 20. Je divise : 10 divisé par 20, ça fait 0,5. La moitié. Tu vois, le calcul dit exactement ce que ton intuition disait déjà.",
          board: frame(
            "EXEMPLE",
            "20 élèves, dont 10 filles",
            "~",
            "> partie = 10",
            "> total = 20",
            "= 10 ÷ 20 = 0,5",
            "! 0,5 = la moitié",
          ),
        },
        {
          strategy: "analogie",
          say: "Imagine une tablette de chocolat de 20 carrés. Tu en manges 10. La proportion mangée, c'est le nombre de carrés mangés par rapport aux carrés du départ. Tu ne comptes pas seulement ce que tu as mangé : tu le compares toujours à la tablette entière.",
          board: frame(
            "ANALOGIE",
            "Tablette de 20 carrés",
            "■■■■■■■■■■ □□□□□□□□□□",
            "~",
            "mangés : 10   sur   20",
            "= 10 ÷ 20 = 0,5",
          ),
        },
        {
          strategy: "visuel",
          say: "Regarde la barre au tableau. Elle représente le total. La zone pleine représente la partie. La proportion, c'est simplement quelle fraction de la barre est remplie.",
          board: frame(
            "REPRÉSENTATION",
            "total  ├──────────────────────┤",
            "partie ├───────────┤",
            "~",
            "! La proportion, c'est la longueur remplie",
            "! divisée par la longueur totale",
          ),
        },
        {
          strategy: "demonstration",
          say: "Reprenons complètement, très lentement. Étape une : j'identifie le total, c'est l'ensemble dont je parle. Étape deux : j'identifie la partie, c'est le sous-ensemble qui m'intéresse. Étape trois : je divise la partie par le total. Trois étapes, toujours les mêmes, quel que soit l'exercice.",
          board: frame(
            "MÉTHODE",
            "> 1. Repérer le TOTAL (l'ensemble)",
            "> 2. Repérer la PARTIE (ce qui m'intéresse)",
            "> 3. Diviser partie ÷ total",
            "~",
            "! Le total est toujours au dénominateur",
          ),
        },
      ],
      checks: [
        {
          id: "p-c1",
          dimension: "comprendre",
          prompt: "Avec tes propres mots : quand on calcule une proportion, qu'est-ce qu'on compare exactement ?",
          expect: { kind: "keywords", any: ["partie", "total", "ensemble", "divise", "rapport"], min: 2 },
          debrief: "Une proportion compare toujours une PARTIE à un TOTAL. Si tu sais nommer ces deux nombres, tu ne te tromperas plus de division.",
        },
        {
          id: "p-c2",
          dimension: "identifier",
          prompt: "« Sur 40 places de parking, 30 sont occupées. » Quel nombre est le total ? (a) 30 · (b) 40 · (c) 10",
          expect: { kind: "choice", options: ["30", "40", "10"], correct: 1 },
          debrief: "Le total, c'est l'ensemble dont on parle : les 40 places. Les 30 occupées, c'est la partie.",
        },
        {
          id: "p-c3",
          dimension: "appliquer",
          prompt: "12 élèves sur 48 portent des lunettes. Quelle est la proportion, sous forme décimale ?",
          expect: { kind: "number", value: 0.25, tolerance: 0.005 },
          debrief: "12 ÷ 48 = 0,25. Un quart des élèves.",
        },
        {
          id: "p-c4",
          dimension: "raisonner",
          prompt: "Explique-moi pourquoi une proportion est toujours comprise entre 0 et 1.",
          expect: { kind: "open", goodSigns: ["partie", "total", "plus petite", "inferieure", "divise", "jamais plus"] },
          debrief: "Parce que la partie est incluse dans le total : elle ne peut pas être plus grande que lui. Diviser un nombre par un nombre plus grand donne toujours un résultat inférieur à 1.",
        },
      ],
      exercises: [
        {
          id: "p-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Sur 50 places de cinéma, 20 sont occupées. Quelle est la proportion de places occupées (en décimal) ?",
          expect: { kind: "number", value: 0.4, tolerance: 0.005 },
          hints: [
            "Commence par repérer les deux nombres : lequel est le total ?",
            "Le total, c'est 50. La partie, c'est 20. Il ne reste qu'une opération à faire.",
            "Calcule 20 ÷ 50.",
          ],
          guided: [
            { question: "Que cherche-t-on : la partie, le total, ou la proportion ?", expect: { kind: "keywords", any: ["proportion"], min: 1 } },
            { question: "Quel est le total ici ?", expect: { kind: "number", value: 50 } },
            { question: "Quelle est la partie ?", expect: { kind: "number", value: 20 } },
            { question: "Alors, combien vaut 20 ÷ 50 ?", expect: { kind: "number", value: 0.4, tolerance: 0.005 } },
          ],
          solution: ["Total = 50 places", "Partie = 20 places occupées", "20 ÷ 50 = 0,4"],
        },
        {
          id: "p-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Dans une classe de 32 élèves, 24 ont réussi l'examen. Quelle est la proportion de réussite ?",
          expect: { kind: "number", value: 0.75, tolerance: 0.005 },
          hints: [
            "Le total n'est pas 24. Relis la phrase.",
            "Total = 32 élèves, partie = 24 réussites.",
            "Calcule 24 ÷ 32.",
          ],
          solution: ["Total = 32", "Partie = 24", "24 ÷ 32 = 0,75"],
        },
        {
          id: "p-e3",
          difficulty: 3,
          dimension: "raisonner",
          prompt: "Classe A : 12 réussites sur 20. Classe B : 18 réussites sur 30. Quelle classe a la meilleure proportion de réussite, et pourquoi ?",
          expect: { kind: "keywords", any: ["meme", "egale", "identique", "pareil", "autant", "0,6", "0.6"], min: 1 },
          hints: [
            "Ne compare pas 12 et 18 directement : les totaux ne sont pas les mêmes.",
            "Calcule les deux proportions séparément, puis compare-les.",
            "12 ÷ 20 = 0,6 et 18 ÷ 30 = 0,6.",
          ],
          solution: ["12 ÷ 20 = 0,6", "18 ÷ 30 = 0,6", "Les deux classes réussissent exactement dans la même proportion."],
        },
        {
          id: "p-e4",
          difficulty: 4,
          dimension: "appliquer",
          prompt: "Dans un immeuble de 12 appartements, 3 sont vides. Quelle est la proportion d'appartements OCCUPÉS ?",
          expect: { kind: "number", value: 0.75, tolerance: 0.005 },
          hints: [
            "Attention : on te donne les vides, on te demande les occupés.",
            "Combien d'appartements sont occupés ? 12 − 3.",
            "Calcule 9 ÷ 12.",
          ],
          solution: ["Occupés = 12 − 3 = 9", "9 ÷ 12 = 0,75"],
        },
        {
          id: "p-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : une équipe gagne 7 matchs sur 10, puis 3 sur 5. Quelle est sa proportion de victoires sur l'ensemble de la saison ?",
          expect: { kind: "number", value: 0.667, tolerance: 0.02 },
          hints: [
            "On ne fait pas la moyenne de 0,7 et 0,6 : les deux séries n'ont pas le même nombre de matchs.",
            "Additionne les victoires d'un côté, les matchs de l'autre.",
            "Calcule (7 + 3) ÷ (10 + 5).",
          ],
          solution: ["Victoires = 7 + 3 = 10", "Matchs = 10 + 5 = 15", "10 ÷ 15 ≈ 0,667"],
        },
      ],
      pitfalls: [
        {
          id: "p-swap",
          label: "Division inversée (total ÷ partie)",
          detector: { kind: "swapped", value: 2.5 },
          diagnosis: "Tu as divisé le total par la partie au lieu de l'inverse.",
          remediation: "Retiens l'ordre en lisant la phrase à voix haute : « 20 places occupées SUR 50 ». Ce qui suit le mot « sur » va toujours en dessous.",
        },
        {
          id: "p-cent",
          label: "Proportion et pourcentage confondus",
          detector: { kind: "factor", factor: 100 },
          diagnosis: "Ton calcul est juste, mais tu as donné un pourcentage alors que je demandais la proportion décimale.",
          remediation: "La proportion, c'est le résultat de la division : 0,4. Le pourcentage, c'est cette même proportion multipliée par 100 : 40 %. Même information, deux habillages.",
        },
      ],
      summary: {
        know: [
          "Repérer la partie et le total dans un énoncé",
          "Calculer une proportion avec partie ÷ total",
          "Comparer deux proportions de totaux différents",
        ],
        retain: "Proportion = partie ÷ total. Ce qui suit le mot « sur » passe au dénominateur.",
        skill: "Tu sais transformer une situation concrète en une division juste.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    pourcentage: {
      id: "pourcentage",
      title: "Du décimal au pourcentage",
      objective: "Savoir exprimer une proportion en pourcentage et interpréter correctement le résultat.",
      level: 2,
      prerequisites: ["proportion"],
      keywords: ["pourcentage", "cent", "proportion"],
      explanations: [
        {
          strategy: "simple",
          say: "Tu sais maintenant calculer une proportion. Le pourcentage, c'est la même information, mais ramenée sur 100. Pourquoi sur 100 ? Parce que 0,4 ne parle pas à grand monde, alors que 40 %, tout le monde voit ce que ça veut dire.",
          board: frame(
            "LES POURCENTAGES",
            "# Définition",
            "Une proportion ramenée sur 100",
            "~",
            "# Formule",
            "= p = partie ÷ total × 100",
          ),
        },
        {
          strategy: "demonstration",
          say: "Regarde le calcul se construire. 20 élèves sur 50. Je divise d'abord : 20 sur 50, ça fait 0,4. Puis je multiplie par 100 : j'obtiens 40. Donc 40 pour cent. Le « pour cent » signifie littéralement « pour cent élèves ».",
          board: frame(
            "EXEMPLE",
            "20 élèves sur 50",
            "~",
            "> 20 ÷ 50 = 0,4",
            "> 0,4 × 100 = 40",
            "= p = 40 %",
            "! 40 élèves pour 100 élèves",
          ),
        },
        {
          strategy: "analogie",
          say: "Pense à une classe imaginaire de 100 élèves. Le pourcentage répond à une seule question : si le groupe faisait exactement 100 personnes, combien seraient concernées ? C'est un traducteur universel — il permet de comparer une classe de 23 élèves avec une ville de 300 000 habitants.",
          board: frame(
            "POURQUOI 100 ?",
            "Classe de 50  →  40 %",
            "Ville de 300 000  →  40 %",
            "~",
            "! Le pourcentage rend deux groupes comparables",
          ),
        },
        {
          strategy: "visuel",
          say: "Au tableau, chaque carré vaut un pour cent. Quarante carrés remplis, ça se voit tout de suite : c'est un peu moins que la moitié.",
          board: frame(
            "40 % EN IMAGE",
            "■■■■■■■■■■ ■■■■■■■■■■",
            "■■■■■■■■■■ ■■■■■■■■■■",
            "□□□□□□□□□□ □□□□□□□□□□",
            "□□□□□□□□□□ □□□□□□□□□□",
            "□□□□□□□□□□ □□□□□□□□□□",
            "~",
            "! 40 carrés remplis sur 100",
          ),
        },
      ],
      checks: [
        {
          id: "pc-c1",
          dimension: "comprendre",
          prompt: "Que signifie concrètement la phrase « 40 % des élèves portent des lunettes » ?",
          expect: { kind: "keywords", any: ["100", "cent", "sur cent", "quarante"], min: 1 },
          debrief: "Cela veut dire : 40 élèves sur 100. Le pourcentage ramène toujours la situation à un groupe imaginaire de 100.",
        },
        {
          id: "pc-c2",
          dimension: "identifier",
          prompt: "Pour passer d'une proportion (0,35) à un pourcentage, que fait-on ? (a) on divise par 100 · (b) on multiplie par 100 · (c) on ajoute 100",
          expect: { kind: "choice", options: ["on divise par 100", "on multiplie par 100", "on ajoute 100"], correct: 1 },
          debrief: "On multiplie par 100 : 0,35 × 100 = 35 %.",
        },
        {
          id: "pc-c3",
          dimension: "appliquer",
          prompt: "Sur 30 élèves, 12 ont réussi. Quel est le pourcentage de réussite ?",
          expect: { kind: "number", value: 40, tolerance: 0.5, unit: "%" },
          debrief: "12 ÷ 30 = 0,4 puis × 100 = 40 %.",
        },
        {
          id: "pc-c4",
          dimension: "raisonner",
          prompt: "Une classe de 10 élèves a 3 absents, une autre de 200 élèves en a 40. Laquelle a le plus gros problème d'absentéisme, et pourquoi ?",
          expect: { kind: "open", goodSigns: ["30", "20", "pourcentage", "proportion", "premiere", "comparer"] },
          debrief: "30 % contre 20 % : c'est la petite classe qui a le plus gros problème, même si elle compte moins d'absents en nombre. Comparer des effectifs bruts n'a aucun sens quand les totaux diffèrent.",
        },
      ],
      exercises: [
        {
          id: "pc-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Sur 25 questions, tu en réussis 20. Quel est ton pourcentage de réussite ?",
          expect: { kind: "number", value: 80, tolerance: 0.5, unit: "%" },
          hints: ["Fais d'abord la division, le × 100 vient après.", "20 ÷ 25 = 0,8. Et ensuite ?", "0,8 × 100 = 80."],
          guided: [
            { question: "Quel est le total ?", expect: { kind: "number", value: 25 } },
            { question: "Quelle est la proportion (en décimal) ?", expect: { kind: "number", value: 0.8, tolerance: 0.005 } },
            { question: "Et donc, en pourcentage ?", expect: { kind: "number", value: 80, tolerance: 0.5 } },
          ],
          solution: ["20 ÷ 25 = 0,8", "0,8 × 100 = 80", "Réussite : 80 %"],
        },
        {
          id: "pc-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Une commune compte 1 250 habitants, dont 500 ont moins de 20 ans. Quel pourcentage cela représente-t-il ?",
          expect: { kind: "number", value: 40, tolerance: 0.5, unit: "%" },
          hints: ["Les grands nombres ne changent rien à la méthode.", "500 ÷ 1250 = ?", "0,4 × 100 = 40 %."],
          solution: ["500 ÷ 1250 = 0,4", "0,4 × 100 = 40 %"],
        },
        {
          id: "pc-e3",
          difficulty: 3,
          dimension: "raisonner",
          prompt: "Un site annonce « 150 % de clients satisfaits ». Pourquoi est-ce forcément faux ?",
          expect: { kind: "keywords", any: ["plus que le total", "depasser", "impossible", "100", "superieur"], min: 1 },
          hints: [
            "Souviens-toi : la partie peut-elle être plus grande que le total ?",
            "Une proportion reste entre 0 et 1…",
            "…donc un pourcentage de personnes concernées reste entre 0 et 100 %.",
          ],
          solution: ["La partie est incluse dans le total", "La proportion est donc au maximum 1", "Un pourcentage d'un sous-groupe ne peut pas dépasser 100 %"],
        },
        {
          id: "pc-e4",
          difficulty: 4,
          dimension: "appliquer",
          prompt: "Dans un lot de 80 pièces, 68 sont conformes. Quel est le pourcentage de pièces DÉFECTUEUSES ?",
          expect: { kind: "number", value: 15, tolerance: 0.5, unit: "%" },
          hints: [
            "On te donne les conformes, on demande les défectueuses.",
            "80 − 68 = 12 pièces défectueuses.",
            "12 ÷ 80 × 100 = ?",
          ],
          solution: ["Défectueuses = 80 − 68 = 12", "12 ÷ 80 = 0,15", "0,15 × 100 = 15 %"],
        },
        {
          id: "pc-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : 60 % des 40 filles d'une classe font du sport, ainsi que 50 % des 20 garçons. Quel pourcentage de la classe entière fait du sport ?",
          expect: { kind: "number", value: 56.7, tolerance: 0.6, unit: "%" },
          hints: [
            "Interdit de faire la moyenne de 60 et 50 : les deux groupes n'ont pas la même taille.",
            "Combien de filles sportives ? Combien de garçons sportifs ?",
            "24 + 10 = 34 sportifs sur 60 élèves. Termine le calcul.",
          ],
          solution: ["Filles sportives : 60 % de 40 = 24", "Garçons sportifs : 50 % de 20 = 10", "34 ÷ 60 = 0,5667", "≈ 56,7 %"],
        },
      ],
      pitfalls: [
        {
          id: "pc-nocent",
          label: "Oubli du × 100",
          detector: { kind: "factor", factor: 0.01 },
          diagnosis: "Tu t'es arrêté à la proportion : il manque la multiplication par 100.",
          remediation: "Ta division était juste — c'est donc une étape oubliée, pas une incompréhension. Prends l'habitude de te relire : si le résultat est plus petit que 1 alors qu'on demande un pourcentage, c'est le signal.",
        },
        {
          id: "pc-double",
          label: "Multiplication par 100 en trop",
          detector: { kind: "factor", factor: 100 },
          diagnosis: "Tu as multiplié par 100 une valeur qui était déjà un pourcentage.",
          remediation: "Un seul × 100 dans tout le calcul, toujours à la fin. Si ton résultat dépasse 100 % pour un sous-groupe, c'est qu'il y en a eu deux.",
        },
      ],
      summary: {
        know: [
          "Transformer une proportion en pourcentage",
          "Lire un pourcentage comme « tant pour 100 »",
          "Comparer deux groupes de tailles différentes",
        ],
        retain: "p = partie ÷ total × 100. Le × 100 arrive toujours en dernier.",
        skill: "Tu sais exprimer et interpréter un pourcentage sans le confondre avec la proportion.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    "part-dune-quantite": {
      id: "part-dune-quantite",
      title: "Calculer x % d'une quantité",
      objective: "Savoir appliquer un pourcentage donné à une quantité (remises, parts, taxes).",
      level: 3,
      prerequisites: ["pourcentage"],
      keywords: ["pourcentage", "quantite", "remise", "calcul"],
      explanations: [
        {
          strategy: "simple",
          say: "Jusqu'ici tu partais des nombres pour trouver le pourcentage. Maintenant on fait le trajet inverse : on connaît le pourcentage, et on cherche la quantité. C'est la situation des soldes, des taxes, des parts.",
          board: frame(
            "x % D'UNE QUANTITÉ",
            "# Formule",
            "= partie = total × p ÷ 100",
            "~",
            "! On multiplie, on ne divise plus par le total",
          ),
        },
        {
          strategy: "demonstration",
          say: "Un article coûte 80 euros, la remise est de 25 %. Je calcule 80 multiplié par 25, divisé par 100. Ça fait 20 euros de remise. Attention : 20 euros, c'est la remise, pas le prix à payer. Le prix, c'est 80 moins 20, donc 60.",
          board: frame(
            "EXEMPLE",
            "Article : 80 €   Remise : 25 %",
            "~",
            "> 80 × 25 ÷ 100 = 20",
            "= remise = 20 €",
            "> 80 − 20 = 60",
            "! prix payé = 60 €",
          ),
        },
        {
          strategy: "analogie",
          say: "Vois le pourcentage comme une recette de cuisine. 25 %, ça veut dire : pour chaque tranche de 100, j'en prends 25. Ton article de 80 euros, c'est 0,8 tranche de 100 — donc tu prends 0,8 fois 25, c'est-à-dire 20.",
          board: frame(
            "AUTREMENT",
            "25 % = 25 pour chaque 100",
            "~",
            "80 € = 0,8 × 100 €",
            "> 0,8 × 25 = 20 €",
          ),
        },
      ],
      checks: [
        {
          id: "pq-c1",
          dimension: "comprendre",
          prompt: "Quand on cherche « 25 % de 80 », est-ce qu'on divise par 80 ou est-ce qu'on multiplie par 80 ? Explique en une phrase.",
          expect: { kind: "keywords", any: ["multiplie", "multiplication", "fois", "x"], min: 1, forbidden: ["divise par 80"] },
          debrief: "On multiplie : total × p ÷ 100. On ne divise par le total que lorsqu'on CHERCHE le pourcentage.",
        },
        {
          id: "pq-c2",
          dimension: "identifier",
          prompt: "Quelle expression donne 15 % de 200 ? (a) 200 ÷ 15 × 100 · (b) 200 × 15 ÷ 100 · (c) 15 ÷ 200 × 100",
          expect: { kind: "choice", options: ["200 ÷ 15 × 100", "200 × 15 ÷ 100", "15 ÷ 200 × 100"], correct: 1 },
          debrief: "200 × 15 ÷ 100 = 30. La proposition (c) répondrait à une autre question : « quel pourcentage 15 représente-t-il par rapport à 200 ? ».",
        },
        {
          id: "pq-c3",
          dimension: "appliquer",
          prompt: "Combien font 30 % de 250 ?",
          expect: { kind: "number", value: 75, tolerance: 0.5 },
          debrief: "250 × 30 ÷ 100 = 75.",
        },
        {
          id: "pq-c4",
          dimension: "raisonner",
          prompt: "Pourquoi 20 % de 50 € et 50 % de 20 € donnent-ils le même résultat ?",
          expect: { kind: "open", goodSigns: ["multiplication", "ordre", "commutatif", "meme produit", "inverse", "10"] },
          debrief: "Dans les deux cas on calcule 50 × 20 ÷ 100 : la multiplication ne tient pas compte de l'ordre. Les deux valent 10 €.",
        },
      ],
      exercises: [
        {
          id: "pq-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Un manteau coûte 120 €. La remise est de 10 %. Quel est le MONTANT de la remise ?",
          expect: { kind: "number", value: 12, tolerance: 0.5 },
          hints: ["Tu cherches la remise, pas encore le prix final.", "120 × 10 ÷ 100.", "10 % d'un nombre, c'est ce nombre divisé par 10."],
          solution: ["120 × 10 ÷ 100 = 12", "La remise est de 12 €"],
        },
        {
          id: "pq-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Même manteau à 120 €, remise de 10 %. Quel PRIX vas-tu payer ?",
          expect: { kind: "number", value: 108, tolerance: 0.5 },
          hints: ["Tu as déjà calculé la remise : 12 €.", "La remise se soustrait du prix de départ.", "120 − 12."],
          guided: [
            { question: "Quel est le montant de la remise ?", expect: { kind: "number", value: 12, tolerance: 0.5 } },
            { question: "Que fait-on de ce montant : on l'ajoute ou on le retire ?", expect: { kind: "keywords", any: ["retire", "soustrait", "enleve", "moins"], min: 1 } },
            { question: "Quel est donc le prix payé ?", expect: { kind: "number", value: 108, tolerance: 0.5 } },
          ],
          solution: ["Remise : 120 × 10 ÷ 100 = 12 €", "Prix payé : 120 − 12 = 108 €"],
        },
        {
          id: "pq-e3",
          difficulty: 3,
          dimension: "appliquer",
          prompt: "Un loyer de 150 000 FCFA augmente de 6 %. Quel est le nouveau loyer ?",
          expect: { kind: "number", value: 159000, tolerance: 200 },
          hints: ["Calcule d'abord l'augmentation seule.", "150 000 × 6 ÷ 100 = 9 000.", "Ici on ajoute, car le loyer augmente."],
          solution: ["Augmentation : 150 000 × 6 ÷ 100 = 9 000", "Nouveau loyer : 150 000 + 9 000 = 159 000 FCFA"],
        },
        {
          id: "pq-e4",
          difficulty: 4,
          dimension: "raisonner",
          prompt: "Un article subit une remise de 50 %, puis une seconde remise de 50 % sur le nouveau prix. Est-il gratuit ? Justifie.",
          expect: { kind: "keywords", any: ["non", "25", "quart", "pas gratuit"], min: 1 },
          hints: [
            "Prends un prix simple, par exemple 100 €, et déroule.",
            "Après la première remise : 50 €. La seconde remise porte sur 50 €, pas sur 100 €.",
            "50 % de 50 €, ça fait 25 € : il reste 25 €.",
          ],
          solution: ["Prix de départ : 100 €", "Après −50 % : 50 €", "Après −50 % du nouveau prix : 25 €", "Il reste 25 % du prix initial : l'article n'est pas gratuit."],
        },
        {
          id: "pq-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : après une remise de 20 %, tu payes un article 64 €. Quel était son prix avant remise ?",
          expect: { kind: "number", value: 80, tolerance: 0.5 },
          hints: [
            "Les 64 € ne représentent pas 100 % du prix initial. Quel pourcentage représentent-ils ?",
            "Payer après une remise de 20 %, c'est payer 80 % du prix de départ.",
            "Si 80 % valent 64 €, alors 1 % vaut 0,80 € — et 100 % ?",
          ],
          solution: ["Prix payé = 80 % du prix initial", "1 % = 64 ÷ 80 = 0,8 €", "100 % = 0,8 × 100 = 80 €"],
        },
      ],
      pitfalls: [
        {
          id: "pq-confusion",
          label: "Remise confondue avec prix final",
          detector: { kind: "value", value: 12 },
          diagnosis: "Tu as donné le montant de la remise alors que je demandais le prix à payer.",
          remediation: "Relis toujours la dernière phrase de l'énoncé avant de répondre : « montant de la remise » et « prix payé » sont deux questions différentes, et le calcul s'arrête à un endroit différent.",
        },
        {
          id: "pq-divise",
          label: "Division par le pourcentage",
          detector: { kind: "value", value: 1200 },
          diagnosis: "Tu as divisé par le pourcentage au lieu de multiplier.",
          remediation: "Repère la question : si le pourcentage est DONNÉ, il se multiplie. On ne divise par le total que lorsqu'on cherche le pourcentage lui-même.",
        },
      ],
      summary: {
        know: [
          "Calculer x % d'une quantité",
          "Distinguer le montant d'une remise du prix final",
          "Appliquer une hausse ou une baisse",
        ],
        retain: "partie = total × p ÷ 100. Pourcentage donné → on multiplie ; pourcentage cherché → on divise.",
        skill: "Tu sais utiliser un pourcentage dans une situation d'achat ou de variation.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    variation: {
      id: "variation",
      title: "La variation en pourcentage",
      objective: "Savoir calculer et interpréter une évolution entre deux valeurs.",
      level: 4,
      prerequisites: ["part-dune-quantite"],
      keywords: ["variation", "evolution", "hausse", "baisse"],
      explanations: [
        {
          strategy: "simple",
          say: "Une variation compare un avant et un après. Le piège est toujours le même : on compare l'écart à la valeur de DÉPART, jamais à celle d'arrivée.",
          board: frame(
            "LA VARIATION",
            "# Formule",
            "= t = (arrivée − départ) ÷ départ × 100",
            "~",
            "! Le dénominateur, c'est toujours la valeur de départ",
          ),
        },
        {
          strategy: "demonstration",
          say: "Un loyer passe de 200 à 250. L'écart est de 50. Je compare ce 50 à la valeur de départ, 200 : ça fait 0,25, donc 25 %. Le loyer a augmenté de 25 %.",
          board: frame(
            "EXEMPLE",
            "200 €  →  250 €",
            "~",
            "> écart = 250 − 200 = 50",
            "> 50 ÷ 200 = 0,25",
            "= t = +25 %",
          ),
        },
        {
          strategy: "analogie",
          say: "C'est comme mesurer une progression sportive. Gagner 2 kilos de muscle n'a pas le même sens pour quelqu'un qui en pesait 50 ou 100. L'écart seul ne dit rien : il ne devient parlant qu'une fois rapporté au point de départ.",
          board: frame(
            "POURQUOI LE DÉPART ?",
            "+50 € sur 200 €  →  +25 %",
            "+50 € sur 1 000 € →  +5 %",
            "~",
            "! Le même écart, deux réalités différentes",
          ),
        },
      ],
      checks: [
        {
          id: "v-c1",
          dimension: "comprendre",
          prompt: "Dans le calcul d'une variation, par quelle valeur divise-t-on l'écart : celle de départ ou celle d'arrivée ?",
          expect: { kind: "keywords", any: ["depart", "initiale", "avant", "premiere"], min: 1 },
          debrief: "Toujours la valeur de départ. C'est elle qui sert de référence.",
        },
        {
          id: "v-c2",
          dimension: "identifier",
          prompt: "Un prix passe de 50 € à 40 €. Le taux de variation est : (a) positif · (b) négatif · (c) nul",
          expect: { kind: "choice", options: ["positif", "négatif", "nul"], correct: 1 },
          debrief: "40 − 50 = −10 : l'écart est négatif, donc la variation aussi. C'est une baisse de 20 %.",
        },
        {
          id: "v-c3",
          dimension: "appliquer",
          prompt: "Une population passe de 800 à 920 habitants. Quel est le taux de variation en % ?",
          expect: { kind: "number", value: 15, tolerance: 0.5, unit: "%" },
          debrief: "(920 − 800) ÷ 800 × 100 = 120 ÷ 800 × 100 = 15 %.",
        },
        {
          id: "v-c4",
          dimension: "raisonner",
          prompt: "Un prix augmente de 10 %, puis baisse de 10 %. Retrouve-t-il son prix de départ ? Justifie.",
          expect: { kind: "open", goodSigns: ["non", "plus petit", "inferieur", "99", "base differente", "depart"] },
          debrief: "Non : la hausse porte sur le prix initial, la baisse sur un prix plus élevé. 100 → 110 → 99. On perd 1 %.",
        },
      ],
      exercises: [
        {
          id: "v-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Un loyer passe de 100 000 à 120 000 FCFA. Quel est le taux d'augmentation ?",
          expect: { kind: "number", value: 20, tolerance: 0.5, unit: "%" },
          hints: ["Calcule d'abord l'écart.", "Écart = 20 000. Par quoi le divise-t-on ?", "20 000 ÷ 100 000 × 100."],
          solution: ["Écart : 120 000 − 100 000 = 20 000", "20 000 ÷ 100 000 = 0,2", "+20 %"],
        },
        {
          id: "v-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Un article passe de 80 € à 60 €. Quel est le taux de variation ?",
          expect: { kind: "number", value: -25, tolerance: 0.5, unit: "%" },
          hints: ["L'écart est négatif, garde le signe.", "60 − 80 = −20.", "−20 ÷ 80 × 100."],
          solution: ["Écart : 60 − 80 = −20", "−20 ÷ 80 = −0,25", "−25 %"],
        },
        {
          id: "v-e3",
          difficulty: 3,
          dimension: "raisonner",
          prompt: "Deux boutiques annoncent la même hausse de 5 €. La première vendait à 20 €, la seconde à 100 €. Laquelle a le plus augmenté en pourcentage ?",
          expect: { kind: "keywords", any: ["premiere", "20", "25"], min: 1 },
          hints: ["Calcule les deux taux séparément.", "5 ÷ 20 d'un côté, 5 ÷ 100 de l'autre.", "25 % contre 5 %."],
          solution: ["Boutique 1 : 5 ÷ 20 = 25 %", "Boutique 2 : 5 ÷ 100 = 5 %", "La première a bien plus augmenté, en proportion."],
        },
        {
          id: "v-e4",
          difficulty: 4,
          dimension: "appliquer",
          prompt: "Un effectif passe de 250 à 200 élèves. Quel est le taux de variation ?",
          expect: { kind: "number", value: -20, tolerance: 0.5, unit: "%" },
          hints: ["Attention au dénominateur : 250 ou 200 ?", "C'est 250, la valeur de départ.", "−50 ÷ 250 × 100."],
          solution: ["Écart : 200 − 250 = −50", "−50 ÷ 250 = −0,2", "−20 %"],
        },
        {
          id: "v-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : un prix baisse de 20 %, puis augmente de 20 %. Quel est le taux de variation global ?",
          expect: { kind: "number", value: -4, tolerance: 0.5, unit: "%" },
          hints: [
            "Pars d'un prix de 100 € pour rendre le calcul lisible.",
            "Après la baisse : 80 €. La hausse de 20 % porte maintenant sur 80 €, pas sur 100 €.",
            "80 + 16 = 96. Compare 96 à 100.",
          ],
          solution: ["100 → −20 % → 80", "80 → +20 % → 96", "(96 − 100) ÷ 100 = −0,04", "Variation globale : −4 %"],
        },
      ],
      pitfalls: [
        {
          id: "v-arrivee",
          label: "Division par la valeur d'arrivée",
          detector: { kind: "value", value: 16.67 },
          diagnosis: "Tu as divisé l'écart par la valeur d'arrivée au lieu de la valeur de départ.",
          remediation: "Repère la chronologie dans l'énoncé : « passe de … à … ». Le premier nombre cité est la référence, c'est lui qui va au dénominateur.",
        },
        {
          id: "v-signe",
          label: "Signe de la variation oublié",
          detector: { kind: "value", value: 25 },
          diagnosis: "La valeur absolue est juste, mais il s'agit d'une baisse : le taux est négatif.",
          remediation: "Écris toujours l'écart sous la forme arrivée − départ : le signe se calcule tout seul et tu n'as plus à y penser.",
        },
      ],
      summary: {
        know: [
          "Calculer un taux de variation entre deux valeurs",
          "Interpréter le signe du taux",
          "Comprendre pourquoi +10 % puis −10 % ne s'annulent pas",
        ],
        retain: "t = (arrivée − départ) ÷ départ × 100. La référence est toujours la valeur de départ.",
        skill: "Tu sais mesurer et interpréter une évolution en pourcentage.",
      },
    },
  },
};
