import type { Course } from "@/types/monprof";
import { frame } from "../builders";

/* Cours intégré n°2 — la progression complète demandée dans le
   cahier des charges : données → effectifs → fréquences → moyenne →
   médiane → dispersion, avec prérequis chaînés. */

export const STATISTIQUES: Course = {
  id: "statistiques",
  title: "Statistiques descriptives",
  subject: "Mathématiques",
  createdAt: 0,
  origin: "seed",
  chapters: [
    { id: "ch1", title: "Comprendre les données", conceptIds: ["donnees", "effectifs", "frequences"] },
    { id: "ch2", title: "Résumer une série", conceptIds: ["moyenne", "mediane"] },
    { id: "ch3", title: "Mesurer la dispersion", conceptIds: ["dispersion"] },
  ],
  concepts: {
    /* ─────────────────────────────────────────────────────── */
    donnees: {
      id: "donnees",
      title: "Population, échantillon et variable",
      objective: "Savoir nommer ce qu'on étudie, sur qui, et avec quel type de caractère.",
      level: 1,
      prerequisites: [],
      keywords: ["population", "echantillon", "variable", "individu"],
      explanations: [
        {
          strategy: "simple",
          say: "Avant de calculer quoi que ce soit, il faut savoir de quoi on parle. Trois mots suffisent. La population, c'est l'ensemble complet qu'on étudie. L'individu, c'est un élément de cet ensemble. La variable, c'est le caractère qu'on observe sur chaque individu.",
          board: frame(
            "LE VOCABULAIRE",
            "# Population",
            "L'ensemble complet étudié",
            "# Individu",
            "Un élément de cet ensemble",
            "# Variable",
            "Le caractère observé",
          ),
        },
        {
          strategy: "exemple",
          say: "On étudie la taille des élèves d'un lycée de 600 élèves. La population, ce sont les 600 élèves. Un individu, c'est un élève. La variable, c'est la taille. Et si on n'en mesure que 60, ces 60 élèves forment un échantillon.",
          board: frame(
            "EXEMPLE",
            "Lycée de 600 élèves",
            "~",
            "> population = les 600 élèves",
            "> individu = un élève",
            "> variable = la taille",
            "> échantillon = les 60 mesurés",
          ),
        },
        {
          strategy: "visuel",
          say: "Une variable se range dans l'une des deux familles. Quantitative si elle se mesure avec un nombre qui a un sens — une taille, un salaire. Qualitative si elle décrit une catégorie — une couleur, une marque. Ce classement décide de tous les calculs possibles ensuite.",
          board: frame(
            "DEUX FAMILLES",
            "# Quantitative",
            "un nombre qui se calcule : taille, âge, salaire",
            "~",
            "# Qualitative",
            "une catégorie : couleur, sexe, marque",
            "~",
            "! On ne calcule pas la moyenne d'une couleur",
          ),
        },
      ],
      checks: [
        {
          id: "d-c1",
          dimension: "comprendre",
          prompt: "Avec tes mots : quelle est la différence entre la population et l'échantillon ?",
          expect: { kind: "keywords", any: ["ensemble", "tous", "partie", "sous ensemble", "extrait", "petit"], min: 1 },
          debrief: "La population est l'ensemble complet ; l'échantillon n'en est qu'une partie, choisie pour représenter le tout.",
        },
        {
          id: "d-c2",
          dimension: "identifier",
          prompt: "« On interroge 200 clients d'un magasin qui en compte 5 000. » Qu'est-ce qui constitue l'échantillon ? (a) les 5 000 clients · (b) les 200 interrogés · (c) le magasin",
          expect: { kind: "choice", options: ["les 5 000 clients", "les 200 interrogés", "le magasin"], correct: 1 },
          debrief: "Les 200 interrogés forment l'échantillon ; les 5 000 clients sont la population.",
        },
        {
          id: "d-c3",
          dimension: "appliquer",
          prompt: "Sur 1 200 habitants, on interroge 150 personnes. Quelle est la taille de l'échantillon ?",
          expect: { kind: "number", value: 150, tolerance: 0.5 },
          debrief: "150 : c'est le nombre d'individus réellement observés.",
        },
        {
          id: "d-c4",
          dimension: "raisonner",
          prompt: "Pourquoi étudie-t-on souvent un échantillon plutôt que la population entière ?",
          expect: { kind: "open", goodSigns: ["temps", "cout", "trop", "impossible", "rapide", "cher", "grande"] },
          debrief: "Parce qu'interroger tout le monde coûte trop cher, prend trop de temps, ou est matériellement impossible. Un échantillon bien choisi donne une image fidèle à moindre coût.",
        },
      ],
      exercises: [
        {
          id: "d-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Une étude porte sur les 600 élèves d'un lycée ; on en interroge 60. Quelle est la taille de la POPULATION ?",
          expect: { kind: "number", value: 600, tolerance: 0.5 },
          hints: ["La population, c'est l'ensemble complet.", "Lequel des deux nombres désigne tous les élèves ?", "C'est 600."],
          solution: ["Population = ensemble complet = 600 élèves", "Échantillon = 60 élèves interrogés"],
        },
        {
          id: "d-e2",
          difficulty: 2,
          dimension: "identifier",
          prompt: "La couleur des yeux est-elle une variable quantitative ou qualitative ?",
          expect: { kind: "keywords", any: ["qualitative"], min: 1, forbidden: ["quantitative"] },
          hints: ["Peux-tu calculer la moyenne des couleurs ?", "Non : ce n'est pas un nombre, c'est une catégorie.", "Donc elle est qualitative."],
          solution: ["La couleur est une catégorie, pas une mesure", "C'est donc une variable qualitative"],
        },
        {
          id: "d-e3",
          difficulty: 3,
          dimension: "identifier",
          prompt: "Le nombre de frères et sœurs est une variable quantitative. Est-elle discrète (valeurs isolées) ou continue (toutes les valeurs d'un intervalle) ?",
          expect: { kind: "keywords", any: ["discrete"], min: 1, forbidden: ["continue"] },
          hints: ["Peut-on avoir 2,5 frères ?", "Les valeurs possibles sont 0, 1, 2, 3… sans intermédiaire.", "Une variable qui ne prend que des valeurs isolées est discrète."],
          solution: ["On compte 0, 1, 2, 3… jamais 2,5", "La variable est donc quantitative discrète"],
        },
        {
          id: "d-e4",
          difficulty: 4,
          dimension: "raisonner",
          prompt: "Un sondage n'interroge que les personnes sortant d'une salle de sport pour estimer l'activité physique de la ville. Quel est le problème ?",
          expect: { kind: "keywords", any: ["representatif", "biais", "pas representatif", "sportif", "fausse"], min: 1 },
          hints: [
            "Demande-toi qui a une chance d'être interrogé.",
            "Les personnes sédentaires ne passent jamais devant cette salle.",
            "L'échantillon ne ressemble pas à la population : on dit qu'il est biaisé.",
          ],
          solution: ["L'échantillon ne contient que des sportifs", "Il n'est pas représentatif de la population", "Le résultat sera surestimé : c'est un biais de sélection"],
        },
      ],
      pitfalls: [
        {
          id: "d-inv",
          label: "Population et échantillon inversés",
          detector: { kind: "value", value: 60 },
          diagnosis: "Tu as donné l'échantillon alors que je demandais la population.",
          remediation: "Un réflexe simple : la population est toujours le plus grand des deux nombres, puisque l'échantillon en est extrait.",
        },
      ],
      summary: {
        know: ["Distinguer population, individu et échantillon", "Reconnaître une variable quantitative ou qualitative", "Repérer un échantillon non représentatif"],
        retain: "Population = tout le monde. Échantillon = une partie. Variable = ce qu'on observe.",
        skill: "Tu sais décrire correctement la situation avant de calculer.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    effectifs: {
      id: "effectifs",
      title: "Les effectifs",
      objective: "Savoir compter combien d'individus prennent chaque valeur et construire un tableau d'effectifs.",
      level: 2,
      prerequisites: ["donnees"],
      keywords: ["effectif", "total", "tableau"],
      explanations: [
        {
          strategy: "simple",
          say: "L'effectif répond à une seule question : combien de fois ? Combien d'individus prennent cette valeur-là. C'est un comptage, rien de plus — mais c'est la base de tout le reste.",
          board: frame(
            "L'EFFECTIF",
            "# Définition",
            "Nombre d'individus prenant une valeur donnée",
            "~",
            "# Notation",
            "= n = effectif d'une valeur",
            "= N = effectif total",
          ),
        },
        {
          strategy: "demonstration",
          say: "Prenons les notes suivantes : 10, 12, 10, 15, 12, 10. Je compte les 10 : il y en a trois. Les 12 : deux. Les 15 : un. Je range ça dans un tableau, et je vérifie : trois plus deux plus un, ça fait six, et j'avais bien six notes.",
          board: frame(
            "EXEMPLE",
            "Notes : 10, 12, 10, 15, 12, 10",
            "~",
            "valeur   10   12   15",
            "effectif  3    2    1",
            "~",
            "> 3 + 2 + 1 = 6",
            "! N = 6 = nombre de notes",
          ),
        },
        {
          strategy: "analogie",
          say: "C'est exactement ce que fait une caissière qui trie des pièces par valeur. Elle fait des petits tas : un tas de pièces de 100, un tas de 50. La hauteur de chaque tas, c'est l'effectif. Le nombre total de pièces, c'est l'effectif total.",
          board: frame(
            "AUTREMENT",
            "Un tas par valeur",
            "hauteur du tas = effectif",
            "~",
            "! La somme des tas redonne toujours N",
          ),
        },
      ],
      checks: [
        {
          id: "e-c1",
          dimension: "comprendre",
          prompt: "Avec tes mots : que compte exactement un effectif ?",
          expect: { kind: "keywords", any: ["nombre", "combien", "fois", "individus", "compte"], min: 1 },
          debrief: "Un effectif compte le nombre d'individus qui prennent une valeur donnée. Ce n'est jamais la valeur elle-même.",
        },
        {
          id: "e-c2",
          dimension: "identifier",
          prompt: "L'effectif total N, c'est : (a) la plus grande valeur · (b) la somme des effectifs · (c) le nombre de valeurs différentes",
          expect: { kind: "choice", options: ["la plus grande valeur", "la somme des effectifs", "le nombre de valeurs différentes"], correct: 1 },
          debrief: "N est la somme de tous les effectifs : chaque individu est compté une fois et une seule.",
        },
        {
          id: "e-c3",
          dimension: "appliquer",
          prompt: "Série : 2, 3, 3, 5, 3, 2. Quel est l'effectif de la valeur 3 ?",
          expect: { kind: "number", value: 3, tolerance: 0.1 },
          debrief: "La valeur 3 apparaît trois fois : son effectif est 3. Ici la valeur et l'effectif se ressemblent, mais ce sont bien deux choses différentes.",
        },
        {
          id: "e-c4",
          dimension: "raisonner",
          prompt: "Pourquoi la somme des effectifs est-elle toujours égale au nombre d'individus observés ?",
          expect: { kind: "open", goodSigns: ["chaque", "une fois", "individu", "compte", "toutes les valeurs"] },
          debrief: "Parce que chaque individu prend exactement une valeur : il est compté une fois, dans un seul tas. Si la somme ne tombe pas juste, c'est qu'il y a une erreur de comptage.",
        },
      ],
      exercises: [
        {
          id: "e-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Série : 4, 5, 4, 4, 6, 5. Quel est l'effectif de la valeur 4 ?",
          expect: { kind: "number", value: 3, tolerance: 0.1 },
          hints: ["Ne réponds pas 4 : 4 est la valeur, pas le comptage.", "Compte combien de fois le nombre 4 apparaît.", "Il apparaît trois fois."],
          guided: [
            { question: "Que cherche-t-on : une valeur ou un comptage ?", expect: { kind: "keywords", any: ["comptage", "effectif", "combien", "nombre de fois"], min: 1 } },
            { question: "Combien de fois vois-tu le nombre 4 dans la série ?", expect: { kind: "number", value: 3, tolerance: 0.1 } },
          ],
          solution: ["Série : 4, 5, 4, 4, 6, 5", "Le 4 apparaît en positions 1, 3 et 4", "Effectif de 4 = 3"],
        },
        {
          id: "e-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Même série : 4, 5, 4, 4, 6, 5. Quel est l'effectif total N ?",
          expect: { kind: "number", value: 6, tolerance: 0.1 },
          hints: ["N ne compte pas les valeurs différentes, mais les individus.", "Additionne les effectifs : 3 (les 4) + 2 (les 5) + 1 (le 6).", "N = 6."],
          solution: ["Effectifs : 4→3, 5→2, 6→1", "3 + 2 + 1 = 6", "N = 6"],
        },
        {
          id: "e-e3",
          difficulty: 3,
          dimension: "appliquer",
          prompt: "Un tableau donne trois valeurs d'effectifs 5, 8 et 7. Combien d'individus ont été observés ?",
          expect: { kind: "number", value: 20, tolerance: 0.1 },
          hints: ["L'effectif total est la somme des effectifs.", "5 + 8 + 7.", "N = 20."],
          solution: ["N = 5 + 8 + 7 = 20 individus"],
        },
        {
          id: "e-e4",
          difficulty: 4,
          dimension: "raisonner",
          prompt: "Mêmes effectifs 5, 8 et 7 (dans cet ordre). Quel est l'effectif cumulé croissant de la DEUXIÈME valeur, c'est-à-dire le nombre d'individus ayant la 1re ou la 2e valeur ?",
          expect: { kind: "number", value: 13, tolerance: 0.1 },
          hints: ["Cumuler veut dire : additionner au fur et à mesure.", "Pour la 2e valeur, on additionne le 1er et le 2e effectif.", "5 + 8 = 13."],
          solution: ["Cumul 1re valeur : 5", "Cumul 2e valeur : 5 + 8 = 13", "Cumul 3e valeur : 13 + 7 = 20 = N"],
        },
      ],
      pitfalls: [
        {
          id: "e-valeur",
          label: "Valeur confondue avec effectif",
          detector: { kind: "value", value: 4 },
          diagnosis: "Tu m'as donné la valeur observée, pas son effectif.",
          remediation: "Sépare bien les deux colonnes du tableau : en haut, CE QU'ON OBSERVE (la valeur) ; en bas, COMBIEN DE FOIS on l'observe (l'effectif). L'effectif ne peut jamais dépasser N.",
        },
        {
          id: "e-distinctes",
          label: "Effectif total confondu avec nombre de valeurs distinctes",
          detector: { kind: "value", value: 3 },
          diagnosis: "Tu as compté le nombre de valeurs différentes, pas le nombre d'individus.",
          remediation: "Il y a trois valeurs différentes, mais six notes : chaque individu compte. L'effectif total, c'est la somme de la ligne des effectifs.",
        },
      ],
      summary: {
        know: ["Compter l'effectif d'une valeur", "Calculer l'effectif total N", "Construire un tableau d'effectifs et le vérifier"],
        retain: "Effectif = combien de fois. N = somme des effectifs = nombre d'individus.",
        skill: "Tu sais organiser des données brutes en tableau d'effectifs.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    frequences: {
      id: "frequences",
      title: "Les fréquences",
      objective: "Savoir calculer une fréquence, l'exprimer en pourcentage et l'interpréter.",
      level: 3,
      prerequisites: ["effectifs"],
      keywords: ["frequence", "effectif", "pourcentage"],
      explanations: [
        {
          strategy: "simple",
          say: "Un effectif seul ne dit pas grand-chose : 8 élèves, est-ce beaucoup ? Ça dépend du total. La fréquence répond à ça : elle rapporte l'effectif à l'effectif total.",
          board: frame(
            "LA FRÉQUENCE",
            "# Définition",
            "Part que représente un effectif dans le total",
            "~",
            "# Formule",
            "= f = n ÷ N",
            "= f en % = n ÷ N × 100",
          ),
        },
        {
          strategy: "demonstration",
          say: "Sur 40 élèves, 12 pratiquent un sport. Je divise 12 par 40 : j'obtiens 0,3. C'est la fréquence. Multipliée par 100, ça fait 30 pour cent. Même information, deux écritures.",
          board: frame(
            "EXEMPLE",
            "n = 12   N = 40",
            "~",
            "> 12 ÷ 40 = 0,3",
            "> 0,3 × 100 = 30",
            "! f = 0,3 soit 30 %",
          ),
        },
        {
          strategy: "analogie",
          say: "C'est la même mécanique que les pourcentages : l'effectif joue le rôle de la partie, l'effectif total celui du total. Si tu maîtrises l'un, tu maîtrises l'autre — seul le vocabulaire change.",
          board: frame(
            "LE PONT",
            "proportion = partie ÷ total",
            "fréquence  = effectif ÷ effectif total",
            "~",
            "! Même calcul, autre vocabulaire",
          ),
        },
      ],
      checks: [
        {
          id: "f-c1",
          dimension: "comprendre",
          prompt: "Pourquoi une fréquence est-elle plus parlante qu'un effectif brut ?",
          expect: { kind: "keywords", any: ["total", "comparer", "rapport", "proportion", "taille"], min: 1 },
          debrief: "Parce qu'elle tient compte du total : 8 sur 10 et 8 sur 1 000 n'ont rien à voir, alors que l'effectif est le même.",
        },
        {
          id: "f-c2",
          dimension: "identifier",
          prompt: "La fréquence se calcule par : (a) n × N · (b) n ÷ N · (c) N ÷ n",
          expect: { kind: "choice", options: ["n × N", "n ÷ N", "N ÷ n"], correct: 1 },
          debrief: "f = n ÷ N. L'effectif total est toujours au dénominateur.",
        },
        {
          id: "f-c3",
          dimension: "appliquer",
          prompt: "n = 12 et N = 48. Quelle est la fréquence, en décimal ?",
          expect: { kind: "number", value: 0.25, tolerance: 0.005 },
          debrief: "12 ÷ 48 = 0,25, soit 25 %.",
        },
        {
          id: "f-c4",
          dimension: "raisonner",
          prompt: "Pourquoi la somme de toutes les fréquences d'une série vaut-elle toujours 1 (ou 100 %) ?",
          expect: { kind: "open", goodSigns: ["somme des effectifs", "n sur n", "total", "tous les individus", "100"] },
          debrief: "Parce que la somme des effectifs vaut N : on calcule donc N ÷ N, c'est-à-dire 1. C'est un excellent contrôle : si tes fréquences ne totalisent pas 1, il y a une erreur.",
        },
      ],
      exercises: [
        {
          id: "f-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "n = 9, N = 36. Quelle est la fréquence en décimal ?",
          expect: { kind: "number", value: 0.25, tolerance: 0.005 },
          hints: ["Quel nombre est le total ?", "N = 36 va au dénominateur.", "9 ÷ 36 = 0,25."],
          solution: ["f = 9 ÷ 36 = 0,25"],
        },
        {
          id: "f-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Même situation (n = 9, N = 36). Exprime maintenant la fréquence en POURCENTAGE.",
          expect: { kind: "number", value: 25, tolerance: 0.5, unit: "%" },
          hints: ["Tu as déjà 0,25.", "Il manque une seule opération.", "0,25 × 100 = 25."],
          solution: ["f = 0,25", "0,25 × 100 = 25 %"],
        },
        {
          id: "f-e3",
          difficulty: 3,
          dimension: "raisonner",
          prompt: "Une série n'a que trois valeurs. Les fréquences des deux premières sont 0,2 et 0,5. Quelle est la fréquence de la troisième ?",
          expect: { kind: "number", value: 0.3, tolerance: 0.005 },
          hints: ["Souviens-toi de ce que vaut la somme des fréquences.", "Elle vaut toujours 1.", "1 − 0,2 − 0,5 = 0,3."],
          solution: ["Somme des fréquences = 1", "1 − (0,2 + 0,5) = 0,3"],
        },
        {
          id: "f-e4",
          difficulty: 4,
          dimension: "appliquer",
          prompt: "Sur 200 clients, 50 choisissent le produit A. Quelle est la fréquence du produit A, en pourcentage ?",
          expect: { kind: "number", value: 25, tolerance: 0.5, unit: "%" },
          hints: ["Repère n et N avant de calculer.", "n = 50, N = 200.", "50 ÷ 200 × 100."],
          solution: ["f = 50 ÷ 200 = 0,25", "soit 25 %"],
        },
        {
          id: "f-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : dans le groupe A (30 personnes), 60 % aiment le thé ; dans le groupe B (70 personnes), 40 % l'aiment. Quelle est la fréquence globale, en pourcentage, sur les 100 personnes ?",
          expect: { kind: "number", value: 46, tolerance: 0.6, unit: "%" },
          hints: [
            "On ne fait pas la moyenne de 60 et 40 : les groupes n'ont pas la même taille.",
            "Reviens aux effectifs : combien de personnes dans chaque groupe aiment le thé ?",
            "18 + 28 = 46 personnes sur 100.",
          ],
          solution: ["Groupe A : 60 % de 30 = 18", "Groupe B : 40 % de 70 = 28", "Total : 46 sur 100", "f = 46 %"],
        },
      ],
      pitfalls: [
        {
          id: "f-cent",
          label: "Fréquence et pourcentage confondus",
          detector: { kind: "factor", factor: 100 },
          diagnosis: "Ton calcul est bon, mais tu as donné le pourcentage alors que je demandais la fréquence décimale.",
          remediation: "Garde en tête les deux écritures côte à côte : f = 0,25 et f = 25 %. Regarde l'unité demandée dans la question avant de répondre.",
        },
        {
          id: "f-inv",
          label: "Division inversée (N ÷ n)",
          detector: { kind: "swapped", value: 4 },
          diagnosis: "Tu as divisé l'effectif total par l'effectif : le résultat dépasse 1, ce qui est impossible pour une fréquence.",
          remediation: "Contrôle réflexe : une fréquence est toujours entre 0 et 1. Si tu obtiens 4, c'est que la division est à l'envers.",
        },
      ],
      summary: {
        know: ["Calculer f = n ÷ N", "Passer de la fréquence au pourcentage", "Utiliser le fait que la somme des fréquences vaut 1"],
        retain: "f = n ÷ N, toujours entre 0 et 1. En pourcentage : × 100.",
        skill: "Tu sais relativiser un effectif et comparer des groupes de tailles différentes.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    moyenne: {
      id: "moyenne",
      title: "La moyenne",
      objective: "Savoir calculer une moyenne simple puis pondérée, et connaître sa limite.",
      level: 3,
      prerequisites: ["effectifs"],
      keywords: ["moyenne", "somme", "valeurs"],
      explanations: [
        {
          strategy: "simple",
          say: "La moyenne répond à la question : si on redistribuait tout équitablement, combien chacun aurait-il ? On additionne tout, puis on partage en parts égales.",
          board: frame(
            "LA MOYENNE",
            "# Formule",
            "= x̄ = (x₁ + x₂ + … + xₙ) ÷ n",
            "~",
            "! On divise par le NOMBRE de valeurs",
          ),
        },
        {
          strategy: "demonstration",
          say: "Prenons quatre valeurs : 10, 12, 14 et 16. J'additionne : dix plus douze, vingt-deux ; plus quatorze, trente-six ; plus seize, cinquante-deux. Je divise par quatre, puisqu'il y a quatre valeurs. Cinquante-deux divisé par quatre : treize.",
          board: frame(
            "EXEMPLE",
            "Données : 10   12   14   16",
            "~",
            "> 10 + 12 + 14 + 16 = 52",
            "> 52 ÷ 4",
            "= x̄ = 13",
          ),
        },
        {
          strategy: "analogie",
          say: "Imagine quatre piles de jetons de hauteurs différentes. Tu les renverses toutes dans un même tas, puis tu refais quatre piles strictement identiques. La hauteur commune, c'est la moyenne.",
          board: frame(
            "AUTREMENT",
            "▌▌  ▌▌▌  ▌▌▌▌  ▌▌▌▌▌",
            "↓ tout mélanger, puis répartir ↓",
            "▌▌▌  ▌▌▌  ▌▌▌  ▌▌▌",
            "~",
            "! La moyenne égalise",
          ),
        },
        {
          strategy: "reformulation",
          say: "Quand chaque valeur a un poids — un coefficient, un effectif — on ne peut plus additionner bêtement. Chaque valeur est multipliée par son poids, et on divise par la somme des poids. C'est la moyenne pondérée.",
          board: frame(
            "MOYENNE PONDÉRÉE",
            "= x̄ = Σ (valeur × effectif) ÷ N",
            "~",
            "Exemple : 12 (coef 1) et 15 (coef 3)",
            "> (12×1 + 15×3) ÷ 4",
            "> (12 + 45) ÷ 4 = 14,25",
          ),
        },
      ],
      checks: [
        {
          id: "m-c1",
          dimension: "comprendre",
          prompt: "Avec tes mots : que représente la moyenne d'une série ?",
          expect: { kind: "keywords", any: ["partage", "egal", "repartit", "equitable", "somme", "divise", "centre"], min: 1 },
          debrief: "C'est la valeur qu'aurait chaque individu si le total était réparti équitablement entre tous.",
        },
        {
          id: "m-c2",
          dimension: "identifier",
          prompt: "Pour calculer la moyenne, on divise la somme par : (a) la plus grande valeur · (b) le nombre de valeurs · (c) le nombre de valeurs différentes",
          expect: { kind: "choice", options: ["la plus grande valeur", "le nombre de valeurs", "le nombre de valeurs différentes"], correct: 1 },
          debrief: "On divise par n, le nombre total de valeurs — chaque valeur compte, même si elle se répète.",
        },
        {
          id: "m-c3",
          dimension: "appliquer",
          prompt: "Quelle est la moyenne de 5, 7 et 9 ?",
          expect: { kind: "number", value: 7, tolerance: 0.05 },
          debrief: "5 + 7 + 9 = 21, puis 21 ÷ 3 = 7.",
        },
        {
          id: "m-c4",
          dimension: "raisonner",
          prompt: "Pourquoi dit-on que la moyenne est sensible aux valeurs extrêmes ?",
          expect: { kind: "open", goodSigns: ["grande valeur", "tire", "extreme", "deforme", "somme", "augmente"] },
          debrief: "Parce que chaque valeur entre dans la somme : une seule valeur très grande tire la moyenne vers le haut, même si toutes les autres sont basses.",
        },
      ],
      exercises: [
        {
          id: "m-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Calcule la moyenne de : 10, 12, 14, 16.",
          expect: { kind: "number", value: 13, tolerance: 0.05 },
          hints: ["Commence par la somme.", "La somme vaut 52. Par combien divise-t-on ?", "Il y a 4 valeurs : 52 ÷ 4."],
          guided: [
            { question: "Combien vaut la somme des quatre valeurs ?", expect: { kind: "number", value: 52, tolerance: 0.5 } },
            { question: "Combien y a-t-il de valeurs ?", expect: { kind: "number", value: 4, tolerance: 0.1 } },
            { question: "Alors, que vaut la moyenne ?", expect: { kind: "number", value: 13, tolerance: 0.05 } },
          ],
          solution: ["Somme : 10 + 12 + 14 + 16 = 52", "Nombre de valeurs : 4", "x̄ = 52 ÷ 4 = 13"],
        },
        {
          id: "m-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Calcule la moyenne de : 4, 8, 6, 10, 7.",
          expect: { kind: "number", value: 7, tolerance: 0.05 },
          hints: ["Additionne dans l'ordre que tu veux, l'ordre ne change rien.", "La somme vaut 35.", "35 ÷ 5 = 7."],
          solution: ["Somme : 4 + 8 + 6 + 10 + 7 = 35", "x̄ = 35 ÷ 5 = 7"],
        },
        {
          id: "m-e3",
          difficulty: 3,
          dimension: "appliquer",
          prompt: "Un élève a 12 en devoir (coefficient 1) et 15 à l'examen (coefficient 3). Quelle est sa moyenne ?",
          expect: { kind: "number", value: 14.25, tolerance: 0.05 },
          hints: [
            "On ne peut pas faire (12 + 15) ÷ 2 : les deux notes n'ont pas le même poids.",
            "Multiplie chaque note par son coefficient, puis divise par la somme des coefficients.",
            "(12×1 + 15×3) ÷ 4.",
          ],
          solution: ["12 × 1 = 12", "15 × 3 = 45", "Somme : 57 ; somme des coefficients : 4", "x̄ = 57 ÷ 4 = 14,25"],
        },
        {
          id: "m-e4",
          difficulty: 4,
          dimension: "raisonner",
          prompt: "La série 8, 9, 10 a pour moyenne 9. On ajoute la valeur 40. Que devient la moyenne ?",
          expect: { kind: "number", value: 16.75, tolerance: 0.05 },
          hints: ["N'oublie pas que le nombre de valeurs change aussi.", "Nouvelle somme : 27 + 40 = 67. Nouveau n : 4.", "67 ÷ 4 = 16,75."],
          solution: ["Somme : 8 + 9 + 10 + 40 = 67", "n = 4", "x̄ = 67 ÷ 4 = 16,75", "Une seule valeur extrême a presque doublé la moyenne."],
        },
        {
          id: "m-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : la moyenne de 5 valeurs est 12. Quatre d'entre elles valent 10, 11, 13 et 14. Quelle est la cinquième ?",
          expect: { kind: "number", value: 12, tolerance: 0.05 },
          hints: [
            "Remonte le calcul à l'envers : si la moyenne vaut 12 pour 5 valeurs, que vaut la somme totale ?",
            "Somme totale = 12 × 5 = 60.",
            "60 − (10 + 11 + 13 + 14).",
          ],
          solution: ["Somme totale = 12 × 5 = 60", "Somme des quatre connues = 48", "Cinquième valeur = 60 − 48 = 12"],
        },
      ],
      pitfalls: [
        {
          id: "m-nodiv",
          label: "Division finale oubliée",
          detector: { kind: "value", value: 52 },
          diagnosis: "Tu t'es arrêté à la somme : il manque la division.",
          remediation: "Contrôle réflexe : la moyenne est toujours comprise entre la plus petite et la plus grande valeur. 52 n'est pas entre 10 et 16, donc ce n'est pas une moyenne.",
        },
        {
          id: "m-pond",
          label: "Coefficients ignorés",
          detector: { kind: "value", value: 13.5 },
          diagnosis: "Tu as fait (12 + 15) ÷ 2 : tu as ignoré les coefficients.",
          remediation: "Quand une note pèse 3, c'est comme si elle était écrite trois fois. Réécris la série en entier : 12, 15, 15, 15 — puis fais une moyenne simple. Tu retrouves 14,25.",
        },
      ],
      summary: {
        know: ["Calculer une moyenne simple", "Calculer une moyenne pondérée", "Voir l'effet d'une valeur extrême"],
        retain: "x̄ = somme ÷ nombre de valeurs. Avec des poids : Σ(valeur × poids) ÷ Σ poids.",
        skill: "Tu sais résumer une série par sa valeur centrale et en connaître la limite.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    mediane: {
      id: "mediane",
      title: "La médiane",
      objective: "Savoir déterminer la médiane d'une série et expliquer pourquoi elle complète la moyenne.",
      level: 4,
      prerequisites: ["moyenne"],
      keywords: ["mediane", "ordonner", "milieu"],
      explanations: [
        {
          strategy: "simple",
          say: "La médiane coupe la série en deux moitiés égales : la moitié des valeurs en dessous, la moitié au-dessus. Et il y a une règle non négociable : on ordonne d'abord.",
          board: frame(
            "LA MÉDIANE",
            "# Définition",
            "Valeur qui partage la série ordonnée en deux moitiés",
            "~",
            "! Étape 1 obligatoire : ORDONNER",
          ),
        },
        {
          strategy: "demonstration",
          say: "Série : 7, 3, 9, 1, 5. J'ordonne : 1, 3, 5, 7, 9. Il y a cinq valeurs, donc un milieu net : la troisième, c'est 5. Si le nombre de valeurs est pair, il n'y a pas de milieu unique : on prend la moyenne des deux valeurs centrales.",
          board: frame(
            "EXEMPLE",
            "brut : 7  3  9  1  5",
            "> ordonné : 1  3  5  7  9",
            "~",
            "n impair = 5  →  valeur du milieu",
            "= médiane = 5",
            "~",
            "# Si n est pair",
            "= médiane = moyenne des 2 valeurs centrales",
          ),
        },
        {
          strategy: "analogie",
          say: "Aligne les élèves par taille dans la cour. La médiane, c'est la taille de celui qui se trouve pile au milieu de la file. Si un géant arrive au bout de la file, la moyenne bouge beaucoup — mais celui du milieu, lui, bouge à peine.",
          board: frame(
            "POURQUOI C'EST UTILE",
            "Série : 1  2  3  4  100",
            "~",
            "> moyenne = 22",
            "> médiane = 3",
            "! La médiane résiste aux valeurs extrêmes",
          ),
        },
      ],
      checks: [
        {
          id: "md-c1",
          dimension: "comprendre",
          prompt: "Avec tes mots : que garantit la médiane par rapport à la série ?",
          expect: { kind: "keywords", any: ["moitie", "milieu", "partage", "deux", "50"], min: 1 },
          debrief: "Elle partage la série en deux moitiés : autant de valeurs en dessous qu'au-dessus.",
        },
        {
          id: "md-c2",
          dimension: "identifier",
          prompt: "Quelle est la toute première chose à faire pour trouver une médiane ?",
          expect: { kind: "keywords", any: ["ordonner", "ranger", "trier", "croissant", "classer"], min: 1 },
          debrief: "Ordonner la série. Sans cet ordre, la valeur du milieu ne veut rien dire.",
        },
        {
          id: "md-c3",
          dimension: "appliquer",
          prompt: "Quelle est la médiane de : 3, 7, 5, 9, 11 ?",
          expect: { kind: "number", value: 7, tolerance: 0.05 },
          debrief: "Ordonnée : 3, 5, 7, 9, 11. Cinq valeurs, la troisième est la médiane : 7.",
        },
        {
          id: "md-c4",
          dimension: "raisonner",
          prompt: "Pourquoi utilise-t-on souvent la médiane plutôt que la moyenne pour parler des salaires ?",
          expect: { kind: "open", goodSigns: ["extreme", "tres hauts", "resiste", "deforme", "riches", "representatif"] },
          debrief: "Parce que quelques salaires très élevés tirent la moyenne vers le haut, ce qui donne une fausse idée du salaire « habituel ». La médiane, elle, n'est pas déformée par ces extrêmes.",
        },
      ],
      exercises: [
        {
          id: "md-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Quelle est la médiane de : 4, 8, 6 ?",
          expect: { kind: "number", value: 6, tolerance: 0.05 },
          hints: ["Ordonne d'abord.", "Ordonnée : 4, 6, 8.", "Trois valeurs : la médiane est celle du milieu."],
          solution: ["Ordonnée : 4, 6, 8", "Médiane = 6"],
        },
        {
          id: "md-e2",
          difficulty: 2,
          dimension: "appliquer",
          prompt: "Quelle est la médiane de : 2, 4, 6, 8 ?",
          expect: { kind: "number", value: 5, tolerance: 0.05 },
          hints: ["Ici n est pair : il n'y a pas de valeur unique au milieu.", "Les deux valeurs centrales sont 4 et 6.", "Fais leur moyenne : (4 + 6) ÷ 2."],
          guided: [
            { question: "La série est-elle déjà ordonnée ?", expect: { kind: "keywords", any: ["oui", "deja", "ordonnee"], min: 1 } },
            { question: "Quelles sont les deux valeurs centrales ?", expect: { kind: "keywords", any: ["4 et 6", "4,6", "4 6"], min: 1 } },
            { question: "Que vaut leur moyenne ?", expect: { kind: "number", value: 5, tolerance: 0.05 } },
          ],
          solution: ["n = 4, pair", "Valeurs centrales : 4 et 6", "Médiane = (4 + 6) ÷ 2 = 5"],
        },
        {
          id: "md-e3",
          difficulty: 3,
          dimension: "appliquer",
          prompt: "Quelle est la médiane de : 9, 1, 7, 3, 12, 15 ?",
          expect: { kind: "number", value: 8, tolerance: 0.05 },
          hints: [
            "Surtout, ne prends pas les deux nombres du milieu de la liste telle qu'elle est écrite.",
            "Ordonnée : 1, 3, 7, 9, 12, 15.",
            "Valeurs centrales : 7 et 9 → (7 + 9) ÷ 2.",
          ],
          solution: ["Ordonnée : 1, 3, 7, 9, 12, 15", "n = 6, pair → valeurs centrales 7 et 9", "Médiane = 8"],
        },
        {
          id: "md-e4",
          difficulty: 4,
          dimension: "raisonner",
          prompt: "Dans une entreprise, 9 employés gagnent 200 000 FCFA et le patron 5 000 000. Quel indicateur décrit le mieux « ce que gagne un employé » : la moyenne ou la médiane ? Justifie.",
          expect: { kind: "keywords", any: ["mediane"], min: 1, forbidden: [] },
          hints: [
            "Calcule mentalement la moyenne : elle sera tirée par le salaire du patron.",
            "La moyenne dépasse 680 000, alors que 9 personnes sur 10 gagnent 200 000.",
            "L'indicateur qui résiste à cette valeur extrême est la médiane.",
          ],
          solution: ["Moyenne = (9 × 200 000 + 5 000 000) ÷ 10 = 680 000", "Médiane = 200 000", "La médiane décrit mieux la réalité des employés."],
        },
        {
          id: "md-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : une série contient 10 valeurs ordonnées. Comment obtient-on la médiane ?",
          expect: { kind: "keywords", any: ["5e et 6e", "cinquieme", "moyenne des deux", "deux valeurs centrales"], min: 1 },
          hints: ["10 est pair.", "Le milieu tombe entre deux valeurs.", "On prend la moyenne de la 5e et de la 6e."],
          solution: ["n = 10 est pair", "Les valeurs centrales sont la 5e et la 6e", "Médiane = moyenne de ces deux valeurs"],
        },
      ],
      pitfalls: [
        {
          id: "md-noorder",
          label: "Série non ordonnée",
          detector: { kind: "value", value: 5 },
          diagnosis: "Tu as pris les deux nombres situés au milieu de la liste telle qu'elle est écrite, sans l'ordonner.",
          remediation: "Prends l'habitude de réécrire la série ordonnée sur une ligne à part avant toute chose. Une médiane calculée sur une série non triée est toujours fausse.",
        },
        {
          id: "md-moyenne",
          label: "Médiane confondue avec moyenne",
          detector: { kind: "value", value: 7.83 },
          diagnosis: "Tu as calculé la moyenne de la série, pas sa médiane.",
          remediation: "La moyenne se calcule, la médiane se repère. Pour la médiane, aucune addition de toutes les valeurs : on ordonne, puis on pointe le milieu.",
        },
      ],
      summary: {
        know: ["Ordonner une série avant tout calcul", "Trouver la médiane selon que n est pair ou impair", "Choisir entre moyenne et médiane"],
        retain: "Médiane = valeur du milieu de la série ORDONNÉE. n pair → moyenne des deux centrales.",
        skill: "Tu sais choisir l'indicateur adapté à la forme de la série.",
      },
    },

    /* ─────────────────────────────────────────────────────── */
    dispersion: {
      id: "dispersion",
      title: "Étendue, variance et écart-type",
      objective: "Savoir mesurer la dispersion d'une série et interpréter un écart-type.",
      level: 5,
      prerequisites: ["moyenne", "mediane"],
      keywords: ["etendue", "variance", "ecart-type", "dispersion"],
      explanations: [
        {
          strategy: "simple",
          say: "Deux classes peuvent avoir exactement la même moyenne et être complètement différentes : dans l'une tout le monde tourne autour de 10, dans l'autre il y a des 2 et des 18. La moyenne ne dit rien de ça. Il faut mesurer l'écartement.",
          board: frame(
            "MESURER LA DISPERSION",
            "# Étendue",
            "= plus grande valeur − plus petite",
            "~",
            "# Variance",
            "= moyenne des carrés des écarts à x̄",
            "~",
            "# Écart-type",
            "= σ = √variance",
          ),
        },
        {
          strategy: "demonstration",
          say: "Prenons la série 2, 4, 4, 4, 5, 5, 7, 9. Sa moyenne vaut 5. Je calcule chaque écart à la moyenne, je les élève au carré, j'en fais la moyenne : j'obtiens 4, c'est la variance. Je prends la racine carrée : 2. C'est l'écart-type.",
          board: frame(
            "EXEMPLE",
            "2  4  4  4  5  5  7  9      x̄ = 5",
            "~",
            "> écarts : −3 −1 −1 −1 0 0 2 4",
            "> carrés :  9  1  1  1 0 0 4 16 = 32",
            "> variance = 32 ÷ 8 = 4",
            "= σ = √4 = 2",
          ),
        },
        {
          strategy: "analogie",
          say: "L'écart-type, c'est la distance typique entre un individu et la moyenne. Un écart-type de 2 sur une moyenne de 5 signifie : en gros, les valeurs se promènent autour de 5, à deux unités près. Plus il est grand, plus le groupe est hétérogène.",
          board: frame(
            "INTERPRÉTER σ",
            "σ petit  →  groupe homogène",
            "σ grand  →  groupe hétérogène",
            "~",
            "! σ s'exprime dans la même unité que les données",
            "! σ = 0 signifie que toutes les valeurs sont identiques",
          ),
        },
      ],
      checks: [
        {
          id: "s-c1",
          dimension: "comprendre",
          prompt: "Avec tes mots : que mesure l'écart-type ?",
          expect: { kind: "keywords", any: ["dispersion", "ecart", "moyenne", "eloigne", "distance", "regroupe"], min: 1 },
          debrief: "Il mesure à quel point les valeurs s'écartent, en moyenne, de la moyenne de la série.",
        },
        {
          id: "s-c2",
          dimension: "identifier",
          prompt: "L'écart-type est : (a) le carré de la variance · (b) la racine carrée de la variance · (c) la moitié de l'étendue",
          expect: { kind: "choice", options: ["le carré de la variance", "la racine carrée de la variance", "la moitié de l'étendue"], correct: 1 },
          debrief: "σ = √variance. La racine sert à revenir dans l'unité des données, que le carré avait modifiée.",
        },
        {
          id: "s-c3",
          dimension: "appliquer",
          prompt: "Quelle est l'étendue de la série 4, 9, 2, 7 ?",
          expect: { kind: "number", value: 7, tolerance: 0.05 },
          debrief: "9 − 2 = 7.",
        },
        {
          id: "s-c4",
          dimension: "raisonner",
          prompt: "Deux classes ont la même moyenne de 10. La première a un écart-type de 1, la seconde de 5. Que peux-tu en dire ?",
          expect: { kind: "open", goodSigns: ["homogene", "heterogene", "proches", "dispersees", "premiere", "seconde", "regroupe"] },
          debrief: "La première classe est homogène : presque tout le monde est proche de 10. La seconde est hétérogène : on y trouve des résultats très faibles et très forts. Même moyenne, réalités opposées.",
        },
      ],
      exercises: [
        {
          id: "s-e1",
          difficulty: 1,
          dimension: "appliquer",
          prompt: "Quelle est l'étendue de la série 12, 5, 9, 20 ?",
          expect: { kind: "number", value: 15, tolerance: 0.05 },
          hints: ["Repère les deux valeurs extrêmes.", "Maximum 20, minimum 5.", "20 − 5."],
          solution: ["Max = 20, min = 5", "Étendue = 20 − 5 = 15"],
        },
        {
          id: "s-e2",
          difficulty: 3,
          dimension: "appliquer",
          prompt: "Série : 2, 4, 4, 4, 5, 5, 7, 9 (moyenne = 5). Calcule la VARIANCE.",
          expect: { kind: "number", value: 4, tolerance: 0.05 },
          hints: [
            "Commence par les écarts à la moyenne : chaque valeur moins 5.",
            "Élève chaque écart au carré, puis additionne : tu dois trouver 32.",
            "Divise cette somme par le nombre de valeurs : 32 ÷ 8.",
          ],
          guided: [
            { question: "Quel est l'écart à la moyenne de la première valeur (2) ?", expect: { kind: "number", value: -3, tolerance: 0.05 } },
            { question: "Combien vaut la somme des carrés des écarts ?", expect: { kind: "number", value: 32, tolerance: 0.5 } },
            { question: "Et donc la variance ?", expect: { kind: "number", value: 4, tolerance: 0.05 } },
          ],
          solution: ["Écarts : −3, −1, −1, −1, 0, 0, 2, 4", "Carrés : 9, 1, 1, 1, 0, 0, 4, 16 → somme 32", "Variance = 32 ÷ 8 = 4"],
        },
        {
          id: "s-e3",
          difficulty: 3,
          dimension: "appliquer",
          prompt: "Même série. Quel est l'ÉCART-TYPE ?",
          expect: { kind: "number", value: 2, tolerance: 0.05 },
          hints: ["Tu as la variance : 4.", "L'écart-type est la racine carrée de la variance.", "√4 = 2."],
          solution: ["Variance = 4", "σ = √4 = 2"],
        },
        {
          id: "s-e4",
          difficulty: 4,
          dimension: "raisonner",
          prompt: "Une machine A produit des pièces de 100 g en moyenne avec σ = 0,5 g ; une machine B, 100 g en moyenne avec σ = 6 g. Laquelle choisir pour un travail de précision, et pourquoi ?",
          expect: { kind: "keywords", any: ["a", "premiere", "0,5", "0.5"], min: 1 },
          hints: [
            "Les deux machines ont la même moyenne : ce n'est donc pas le critère.",
            "Regarde la régularité : quelle machine s'écarte le moins de sa cible ?",
            "Un écart-type de 0,5 g signifie des pièces bien plus régulières que 6 g.",
          ],
          solution: ["Même moyenne : 100 g pour les deux", "σ(A) = 0,5 g, σ(B) = 6 g", "La machine A est bien plus régulière : c'est elle qu'on choisit."],
        },
        {
          id: "s-e5",
          difficulty: 5,
          dimension: "raisonner",
          prompt: "Défi : dans une série, toutes les valeurs sont égales à 7. Que vaut l'écart-type, et pourquoi ?",
          expect: { kind: "number", value: 0, tolerance: 0.05 },
          hints: ["Que vaut la moyenne d'une telle série ?", "Elle vaut 7 aussi. Donc combien vaut chaque écart à la moyenne ?", "Tous les écarts valent 0 : leur moyenne des carrés aussi."],
          solution: ["Moyenne = 7", "Chaque écart à la moyenne = 0", "Variance = 0 donc σ = 0", "Aucune dispersion : la série est parfaitement homogène."],
        },
      ],
      pitfalls: [
        {
          id: "s-var",
          label: "Variance donnée à la place de l'écart-type",
          detector: { kind: "value", value: 4 },
          diagnosis: "Tu as donné la variance : il manque la racine carrée.",
          remediation: "Retiens l'ordre : d'abord la variance (avec les carrés), ensuite l'écart-type (la racine). La racine sert à revenir dans l'unité des données.",
        },
        {
          id: "s-somme",
          label: "Étendue confondue avec la somme",
          detector: { kind: "value", value: 25 },
          diagnosis: "Tu as additionné les deux extrêmes au lieu de les soustraire.",
          remediation: "Étendue = écart entre le plus grand et le plus petit. C'est une distance, donc une soustraction : max − min.",
        },
      ],
      summary: {
        know: ["Calculer une étendue", "Calculer variance et écart-type", "Interpréter σ pour comparer deux séries"],
        retain: "σ = √variance. Petit σ = groupe homogène, grand σ = groupe dispersé.",
        skill: "Tu sais décrire une série complètement : sa position ET sa dispersion.",
      },
    },
  },
};
